export enum textTypes {
    TITLE_REGULAR = 'TITLE_REGULAR',
    TITLE_MEDIUM = 'TITLE_MEDIUM',
    TITLE_SEMI_BOLD = 'TITLE_SEMI_BOLD',
    SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR',
    SUB_TITLE_MEDIUM = 'SUB_TITLE_MEDIUM',
    SUB_TITLE_SEMI_BOLD = 'SUB_TITLE_SEMI_BOLD',
    PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
    PARAGRAPH_MEDIUM = 'PARAGRAPH_MEDIUM',
    PARAGRAPH_SEMI_BOLD = 'PARAGRAPH_SEMI_BOLD',
    PARAGRAPH_LIGTH = 'PARAGRAPH_LIGTH',
}